require("core.plugins")
require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.autopairs")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.mason")
require("plugins.lsp")
require("plugins.lspsaga")
require("plugins.null-ls")
require("plugins.treesitter")
